### ISSUE TITLE
'class ChainableLED' has no member named 'init'

### ISSUE THREAD

**Issue by kinselwyn** [Seeed-Studio/Grove_Chainable_RGB_LED#2]
Good day! I am a beginner , I am still studying OOP idk what this means when i run the program it says:                                       Arduino: 1.8.19 (Windows 10), Board: "Arduino Uno"

1_CycleThroughColors:19:8: error: 'class ChainableLED' has no member named 'init'

   leds.init;

        ^~~~

exit status 1

'class ChainableLED' has no member named 'init'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

can you help me with this? what does this mean?

**Comment by ackPeng** [comment]
@kinselwyn I think you should use the ChainableLED class to construct an LEDs object and call the LEDs.init function. The meaning of this error message is: the ChainableLED class does not define an init function, so when you call lesd.init, it will prompt you that it does not have this member function. You can look at the definition of the ChainableLED class.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
